/*==================================================================================================
* Project              : RTD AUTOSAR 4.7
* Platform             : CORTEXM
* Peripheral           : none
* Dependencies         : MemAcc
*
* Autosar Version      : 4.7.0
* Autosar Revision     : ASR_REL_4_7_REV_0000
* Autosar Conf.Variant :
* SW Version           : 6.0.0
* Build Version        : S32K3_RTD_6_0_0_D2506_ASR_REL_4_7_REV_0000_20250610
*
* Copyright 2020 - 2025 NXP
*
* NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be used strictly
* in accordance with the applicable license terms.  By expressly accepting
* such terms or by downloading, installing, activating and/or otherwise using
* the software, you are agreeing that you have read, and that you agree to
* comply with and are bound by, such license terms.  If you do not agree to
* be bound by the applicable license terms, then you may not retain,
* install, activate or otherwise use the software.
*
==================================================================================================*/

#ifndef FEE_CFG_H
#define FEE_CFG_H

/**
*   @file
*
*   @addtogroup FEE
*   @{
*/
/*   @implements Fee_Cfg.h_Artifact*/
#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
                                         INCLUDE FILES
 1) system and project includes
 2) needed interfaces from external units
 3) internal and external interfaces from this unit
==================================================================================================*/
#include "Fee_Types.h"

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/

#define FEE_VENDOR_ID_CFG                    43
#define FEE_AR_RELEASE_MAJOR_VERSION_CFG     4
#define FEE_AR_RELEASE_MINOR_VERSION_CFG     7
#define FEE_AR_RELEASE_REVISION_VERSION_CFG  0
#define FEE_SW_MAJOR_VERSION_CFG             6
#define FEE_SW_MINOR_VERSION_CFG             0
#define FEE_SW_PATCH_VERSION_CFG             0

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
/* Check if current file and MODULENAME configuration header file are of the same vendor */
#if (FEE_VENDOR_ID_CFG != FEE_TYPES_VENDOR_ID)
    #error "Fee_Types.h and Fee_Cfg.h have different vendor ids"
#endif
/* Check if current file and MODULENAME configuration header file are
   of the same Autosar version
*/
#if ((FEE_AR_RELEASE_MAJOR_VERSION_CFG    != FEE_TYPES_AR_RELEASE_MAJOR_VERSION) || \
     (FEE_AR_RELEASE_MINOR_VERSION_CFG    != FEE_TYPES_AR_RELEASE_MINOR_VERSION) || \
     (FEE_AR_RELEASE_REVISION_VERSION_CFG != FEE_TYPES_AR_RELEASE_REVISION_VERSION) \
    )
    #error "AutoSar Version Numbers of Fee_Types.h and Fee_Cfg.h are different"
#endif
/* Check if current file and MODULENAME configuration header file are
   of the same software version
*/
#if ((FEE_SW_MAJOR_VERSION_CFG != FEE_TYPES_SW_MAJOR_VERSION) || \
     (FEE_SW_MINOR_VERSION_CFG != FEE_TYPES_SW_MINOR_VERSION) || \
     (FEE_SW_PATCH_VERSION_CFG != FEE_TYPES_SW_PATCH_VERSION) \
    )
    #error "Software Version Numbers of Fee_Types.h and Fee_Cfg.h are different"
#endif

/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/


/* Pre-processor switch to enable and disable development error detection */
/** @implements   FeeDevErrorDetect_Object */
#define FEE_DEV_ERROR_DETECT                     (STD_OFF)

/* Pre-processor switch to enable / disable the API to read out the modules version information */
/** @implements   FeeVersionInfoApi_Object */
#define FEE_VERSION_INFO_API                     (STD_OFF)

/* The size in bytes to which logical blocks shall be aligned */
/** @implements   FeeVirtualPageSize_Object */
#define FEE_VIRTUAL_PAGE_SIZE                    (8U)

/* Parameter determines the alignment of the start address that Fee buffers need to have */
/** @implements   FeeBufferAlignmentValue_Object */
#define FEE_BUFFER_ALIGN_VALUE                            (1U)

/* Minimum Page size will be a multiple of the minimum page size. Fee shall align read requests to this size */
/** @implements   FeeMinimumReadPageSize_Object */
#define FEE_MINIMUM_READ_PAGE_SIZE               (1U)

/* Job end notification routine provided by the upper layer module (declaration) */
/** @implements   FeeNvmJobEndNotification_Object */
#define FEE_NVM_JOB_END_NOTIFICATION_DECL        

/* Job end notification routine provided by the upper layer module */
/** @implements   FeeNvmJobEndNotification_Object */
#define FEE_NVM_JOB_END_NOTIFICATION             

/* Job error notification routine provided by the upper layer module (declaration) */
/** @implements   FeeNvmJobErrorNotification_Object */
#define FEE_NVM_JOB_ERROR_NOTIFICATION_DECL      

/* Job error notification routine provided by the upper layer module */
/** @implements   FeeNvmJobErrorNotification_Object */
#define FEE_NVM_JOB_ERROR_NOTIFICATION           

/* Job cluster format notification routine provided by the upper layer module (declaration) */
#define FEE_NVM_CLUSTER_FORMAT_NOTIFICATION_DECL 

/* Job cluster format notification routine provided by the upper layer module */
#define FEE_NVM_CLUSTER_FORMAT_NOTIFICATION      
/* Number of configured Fee cluster group */
#define FEE_NUMBER_OF_CLUSTER_GROUPS             (1U)
/* Number of configured Fee blocks */
#define FEE_CRT_CFG_NR_OF_BLOCKS                 (896U)

/* Maximum number of Fee blocks in all project versions and configurations */
#define FEE_MAX_NR_OF_BLOCKS                     (FEE_CRT_CFG_NR_OF_BLOCKS)

/* Management overhead per logical block in bytes */
/** @implements   FeeBlockOverhead_Object */
#define FEE_BLOCK_OVERHEAD                       (32U)

/* Management overhead per logical cluster in bytes */
#define FEE_CLUSTER_OVERHEAD                     (32U)

/* Size of the data buffer in bytes */
#define FEE_DATA_BUFFER_SIZE                     (32U)

/* The contents of an erased flash memory cell */
#define FEE_ERASED_VALUE                         (0xffU)

/* Value of the block and cluster validation flag */
#define FEE_VALIDATED_VALUE                      (0x81U)

/* Value of the block and cluster invalidation flag */
#define FEE_INVALIDATED_VALUE                    (0x18U)

/* If reset, power loss etc. occurs here, neither newly nor previously written data is available */
#define FEE_BLOCK_ALWAYS_AVAILABLE               (STD_OFF)

/* Behavior of Fee_ImmediateBlockErase */
#define FEE_LEGACY_IMM_ERASE_MODE                (STD_OFF)

/* This configuration defines wheather Fee should swap foreign blocks found in flash at swap or not */
#define FEE_SWAP_FOREIGN_BLOCKS_ENABLED          (STD_OFF)

#if (FEE_SWAP_FOREIGN_BLOCKS_ENABLED == STD_ON)

/* This configuration defines for which project the Fee configuration is used  */
#define FEE_BOOTLOADER_CONFIG                    (STD_OFF)
#endif

/* This configuration defines if the status for the never written blocks must be INVALID or INCONSISTENT */
#define FEE_MARK_EMPTY_BLOCKS_INVALID            (STD_OFF)

#define FEE_MEMACC_ADDRESS_AREA_ID_USED          (0U)
/* Symbolic names of configured Fee blocks */
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_0       (1U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_1       (2U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_2       (3U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_3       (4U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_4       (5U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_5       (6U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_6       (7U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_7       (8U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_8       (9U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_9       (10U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_10       (11U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_11       (12U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_12       (13U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_13       (14U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_14       (15U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_15       (16U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_16       (17U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_17       (18U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_18       (19U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_19       (20U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_20       (21U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_21       (22U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_22       (23U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_23       (24U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_24       (25U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_25       (26U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_26       (27U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_27       (28U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_28       (29U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_29       (30U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_30       (31U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_31       (32U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_32       (33U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_33       (34U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_34       (35U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_35       (36U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_36       (37U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_37       (38U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_38       (39U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_39       (40U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_40       (41U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_41       (42U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_42       (43U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_43       (44U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_44       (45U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_45       (46U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_46       (47U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_47       (48U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_48       (49U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_49       (50U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_50       (51U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_51       (52U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_52       (53U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_53       (54U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_54       (55U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_55       (56U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_56       (57U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_57       (58U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_58       (59U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_59       (60U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_60       (61U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_61       (62U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_62       (63U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_63       (64U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_64       (65U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_65       (66U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_66       (67U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_67       (68U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_68       (69U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_69       (70U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_70       (71U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_71       (72U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_72       (73U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_73       (74U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_74       (75U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_75       (76U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_76       (77U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_77       (78U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_78       (79U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_79       (80U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_80       (81U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_81       (82U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_82       (83U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_83       (84U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_84       (85U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_85       (86U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_86       (87U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_87       (88U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_88       (89U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_89       (90U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_90       (91U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_91       (92U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_92       (93U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_93       (94U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_94       (95U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_95       (96U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_96       (97U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_97       (98U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_98       (99U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_99       (100U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_100       (101U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_101       (102U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_102       (103U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_103       (104U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_104       (105U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_105       (106U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_106       (107U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_107       (108U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_108       (109U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_109       (110U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_110       (111U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_111       (112U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_112       (113U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_113       (114U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_114       (115U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_115       (116U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_116       (117U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_117       (118U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_118       (119U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_119       (120U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_120       (121U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_121       (122U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_122       (123U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_123       (124U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_124       (125U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_125       (126U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_126       (127U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_127       (128U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_128       (129U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_129       (130U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_130       (131U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_131       (132U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_132       (133U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_133       (134U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_134       (135U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_135       (136U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_136       (137U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_137       (138U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_138       (139U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_139       (140U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_140       (141U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_141       (142U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_142       (143U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_143       (144U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_144       (145U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_145       (146U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_146       (147U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_147       (148U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_148       (149U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_149       (150U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_150       (151U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_151       (152U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_152       (153U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_153       (154U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_154       (155U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_155       (156U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_156       (157U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_157       (158U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_158       (159U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_159       (160U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_160       (161U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_161       (162U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_162       (163U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_163       (164U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_164       (165U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_165       (166U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_166       (167U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_167       (168U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_168       (169U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_169       (170U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_170       (171U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_171       (172U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_172       (173U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_173       (174U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_174       (175U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_175       (176U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_176       (177U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_177       (178U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_178       (179U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_179       (180U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_180       (181U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_181       (182U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_182       (183U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_183       (184U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_184       (185U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_185       (186U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_186       (187U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_187       (188U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_188       (189U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_189       (190U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_190       (191U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_191       (192U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_192       (193U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_193       (194U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_194       (195U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_195       (196U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_196       (197U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_197       (198U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_198       (199U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_199       (200U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_200       (201U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_201       (202U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_202       (203U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_203       (204U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_204       (205U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_205       (206U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_206       (207U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_207       (208U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_208       (209U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_209       (210U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_210       (211U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_211       (212U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_212       (213U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_213       (214U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_214       (215U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_215       (216U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_216       (217U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_217       (218U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_218       (219U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_219       (220U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_220       (221U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_221       (222U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_222       (223U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_223       (224U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_224       (225U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_225       (226U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_226       (227U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_227       (228U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_228       (229U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_229       (230U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_230       (231U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_231       (232U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_232       (233U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_233       (234U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_234       (235U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_235       (236U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_236       (237U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_237       (238U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_238       (239U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_239       (240U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_240       (241U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_241       (242U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_242       (243U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_243       (244U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_244       (245U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_245       (246U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_246       (247U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_247       (248U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_248       (249U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_249       (250U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_250       (251U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_251       (252U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_252       (253U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_253       (254U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_254       (255U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_255       (256U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_256       (257U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_257       (258U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_258       (259U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_259       (260U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_260       (261U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_261       (262U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_262       (263U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_263       (264U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_264       (265U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_265       (266U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_266       (267U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_267       (268U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_268       (269U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_269       (270U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_270       (271U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_271       (272U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_272       (273U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_273       (274U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_274       (275U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_275       (276U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_276       (277U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_277       (278U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_278       (279U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_279       (280U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_280       (281U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_281       (282U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_282       (283U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_283       (284U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_284       (285U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_285       (286U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_286       (287U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_287       (288U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_288       (289U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_289       (290U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_290       (291U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_291       (292U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_292       (293U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_293       (294U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_294       (295U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_295       (296U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_296       (297U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_297       (298U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_298       (299U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_299       (300U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_300       (301U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_301       (302U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_302       (303U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_303       (304U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_304       (305U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_305       (306U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_306       (307U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_307       (308U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_308       (309U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_309       (310U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_310       (311U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_311       (312U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_312       (313U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_313       (314U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_314       (315U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_315       (316U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_316       (317U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_317       (318U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_318       (319U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_319       (320U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_320       (321U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_321       (322U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_322       (323U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_323       (324U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_324       (325U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_325       (326U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_326       (327U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_327       (328U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_328       (329U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_329       (330U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_330       (331U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_331       (332U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_332       (333U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_333       (334U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_334       (335U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_335       (336U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_336       (337U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_337       (338U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_338       (339U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_339       (340U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_340       (341U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_341       (342U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_342       (343U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_343       (344U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_344       (345U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_345       (346U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_346       (347U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_347       (348U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_348       (349U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_349       (350U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_350       (351U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_351       (352U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_352       (353U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_353       (354U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_354       (355U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_355       (356U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_356       (357U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_357       (358U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_358       (359U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_359       (360U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_360       (361U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_361       (362U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_362       (363U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_363       (364U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_364       (365U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_365       (366U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_366       (367U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_367       (368U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_368       (369U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_369       (370U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_370       (371U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_371       (372U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_372       (373U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_373       (374U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_374       (375U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_375       (376U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_376       (377U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_377       (378U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_378       (379U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_379       (380U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_380       (381U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_381       (382U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_382       (383U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_383       (384U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_384       (385U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_385       (386U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_386       (387U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_387       (388U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_388       (389U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_389       (390U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_390       (391U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_391       (392U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_392       (393U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_393       (394U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_394       (395U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_395       (396U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_396       (397U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_397       (398U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_398       (399U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_399       (400U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_400       (401U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_401       (402U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_402       (403U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_403       (404U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_404       (405U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_405       (406U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_406       (407U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_407       (408U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_408       (409U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_409       (410U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_410       (411U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_411       (412U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_412       (413U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_413       (414U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_414       (415U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_415       (416U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_416       (417U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_417       (418U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_418       (419U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_419       (420U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_420       (421U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_421       (422U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_422       (423U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_423       (424U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_424       (425U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_425       (426U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_426       (427U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_427       (428U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_428       (429U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_429       (430U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_430       (431U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_431       (432U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_432       (433U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_433       (434U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_434       (435U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_435       (436U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_436       (437U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_437       (438U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_438       (439U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_439       (440U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_440       (441U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_441       (442U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_442       (443U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_443       (444U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_444       (445U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_445       (446U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_446       (447U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_447       (448U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_448       (449U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_449       (450U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_450       (451U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_451       (452U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_452       (453U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_453       (454U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_454       (455U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_455       (456U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_456       (457U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_457       (458U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_458       (459U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_459       (460U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_460       (461U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_461       (462U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_462       (463U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_463       (464U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_464       (465U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_465       (466U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_466       (467U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_467       (468U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_468       (469U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_469       (470U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_470       (471U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_471       (472U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_472       (473U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_473       (474U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_474       (475U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_475       (476U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_476       (477U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_477       (478U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_478       (479U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_479       (480U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_480       (481U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_481       (482U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_482       (483U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_483       (484U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_484       (485U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_485       (486U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_486       (487U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_487       (488U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_488       (489U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_489       (490U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_490       (491U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_491       (492U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_492       (493U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_493       (494U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_494       (495U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_495       (496U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_496       (497U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_497       (498U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_498       (499U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_499       (500U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_500       (501U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_501       (502U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_502       (503U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_503       (504U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_504       (505U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_505       (506U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_506       (507U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_507       (508U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_508       (509U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_509       (510U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_510       (511U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_511       (512U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_512       (513U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_513       (514U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_514       (515U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_515       (516U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_516       (517U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_517       (518U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_518       (519U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_519       (520U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_520       (521U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_521       (522U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_522       (523U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_523       (524U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_524       (525U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_525       (526U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_526       (527U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_527       (528U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_528       (529U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_529       (530U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_530       (531U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_531       (532U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_532       (533U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_533       (534U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_534       (535U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_535       (536U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_536       (537U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_537       (538U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_538       (539U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_539       (540U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_540       (541U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_541       (542U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_542       (543U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_543       (544U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_544       (545U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_545       (546U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_546       (547U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_547       (548U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_548       (549U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_549       (550U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_550       (551U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_551       (552U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_552       (553U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_553       (554U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_554       (555U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_555       (556U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_556       (557U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_557       (558U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_558       (559U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_559       (560U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_560       (561U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_561       (562U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_562       (563U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_563       (564U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_564       (565U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_565       (566U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_566       (567U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_567       (568U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_568       (569U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_569       (570U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_570       (571U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_571       (572U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_572       (573U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_573       (574U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_574       (575U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_575       (576U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_576       (577U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_577       (578U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_578       (579U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_579       (580U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_580       (581U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_581       (582U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_582       (583U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_583       (584U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_584       (585U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_585       (586U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_586       (587U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_587       (588U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_588       (589U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_589       (590U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_590       (591U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_591       (592U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_592       (593U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_593       (594U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_594       (595U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_595       (596U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_596       (597U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_597       (598U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_598       (599U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_599       (600U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_600       (601U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_601       (602U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_602       (603U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_603       (604U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_604       (605U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_605       (606U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_606       (607U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_607       (608U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_608       (609U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_609       (610U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_610       (611U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_611       (612U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_612       (613U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_613       (614U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_614       (615U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_615       (616U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_616       (617U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_617       (618U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_618       (619U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_619       (620U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_620       (621U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_621       (622U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_622       (623U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_623       (624U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_624       (625U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_625       (626U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_626       (627U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_627       (628U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_628       (629U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_629       (630U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_630       (631U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_631       (632U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_632       (633U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_633       (634U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_634       (635U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_635       (636U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_636       (637U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_637       (638U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_638       (639U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_639       (640U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_640       (641U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_641       (642U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_642       (643U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_643       (644U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_644       (645U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_645       (646U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_646       (647U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_647       (648U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_648       (649U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_649       (650U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_650       (651U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_651       (652U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_652       (653U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_653       (654U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_654       (655U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_655       (656U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_656       (657U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_657       (658U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_658       (659U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_659       (660U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_660       (661U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_661       (662U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_662       (663U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_663       (664U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_664       (665U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_665       (666U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_666       (667U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_667       (668U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_668       (669U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_669       (670U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_670       (671U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_671       (672U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_672       (673U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_673       (674U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_674       (675U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_675       (676U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_676       (677U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_677       (678U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_678       (679U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_679       (680U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_680       (681U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_681       (682U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_682       (683U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_683       (684U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_684       (685U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_685       (686U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_686       (687U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_687       (688U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_688       (689U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_689       (690U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_690       (691U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_691       (692U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_692       (693U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_693       (694U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_694       (695U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_695       (696U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_696       (697U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_697       (698U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_698       (699U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_699       (700U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_700       (701U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_701       (702U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_702       (703U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_703       (704U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_704       (705U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_705       (706U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_706       (707U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_707       (708U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_708       (709U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_709       (710U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_710       (711U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_711       (712U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_712       (713U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_713       (714U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_714       (715U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_715       (716U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_716       (717U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_717       (718U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_718       (719U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_719       (720U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_720       (721U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_721       (722U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_722       (723U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_723       (724U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_724       (725U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_725       (726U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_726       (727U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_727       (728U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_728       (729U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_729       (730U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_730       (731U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_731       (732U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_732       (733U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_733       (734U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_734       (735U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_735       (736U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_736       (737U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_737       (738U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_738       (739U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_739       (740U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_740       (741U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_741       (742U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_742       (743U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_743       (744U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_744       (745U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_745       (746U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_746       (747U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_747       (748U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_748       (749U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_749       (750U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_750       (751U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_751       (752U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_752       (753U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_753       (754U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_754       (755U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_755       (756U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_756       (757U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_757       (758U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_758       (759U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_759       (760U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_760       (761U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_761       (762U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_762       (763U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_763       (764U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_764       (765U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_765       (766U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_766       (767U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_767       (768U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_768       (769U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_769       (770U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_770       (771U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_771       (772U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_772       (773U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_773       (774U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_774       (775U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_775       (776U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_776       (777U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_777       (778U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_778       (779U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_779       (780U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_780       (781U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_781       (782U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_782       (783U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_783       (784U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_784       (785U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_785       (786U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_786       (787U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_787       (788U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_788       (789U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_789       (790U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_790       (791U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_791       (792U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_792       (793U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_793       (794U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_794       (795U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_795       (796U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_796       (797U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_797       (798U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_798       (799U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_799       (800U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_800       (801U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_801       (802U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_802       (803U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_803       (804U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_804       (805U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_805       (806U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_806       (807U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_807       (808U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_808       (809U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_809       (810U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_810       (811U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_811       (812U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_812       (813U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_813       (814U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_814       (815U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_815       (816U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_816       (817U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_817       (818U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_818       (819U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_819       (820U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_820       (821U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_821       (822U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_822       (823U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_823       (824U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_824       (825U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_825       (826U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_826       (827U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_827       (828U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_828       (829U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_829       (830U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_830       (831U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_831       (832U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_832       (833U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_833       (834U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_834       (835U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_835       (836U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_836       (837U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_837       (838U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_838       (839U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_839       (840U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_840       (841U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_841       (842U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_842       (843U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_843       (844U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_844       (845U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_845       (846U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_846       (847U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_847       (848U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_848       (849U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_849       (850U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_850       (851U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_851       (852U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_852       (853U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_853       (854U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_854       (855U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_855       (856U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_856       (857U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_857       (858U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_858       (859U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_859       (860U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_860       (861U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_861       (862U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_862       (863U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_863       (864U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_864       (865U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_865       (866U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_866       (867U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_867       (868U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_868       (869U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_869       (870U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_870       (871U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_871       (872U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_872       (873U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_873       (874U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_874       (875U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_875       (876U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_876       (877U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_877       (878U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_878       (879U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_879       (880U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_880       (881U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_881       (882U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_882       (883U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_883       (884U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_884       (885U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_885       (886U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_886       (887U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_887       (888U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_888       (889U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_889       (890U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_890       (891U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_891       (892U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_892       (893U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_893       (894U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_894       (895U)
#define FeeConf_FeeBlockConfiguration_FeeBlockConfiguration_895       (896U)

#define FEE_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Fee_MemMap.h"
/* Configuration of cluster group set */
extern const Fee_ClusterGroupType Fee_ClrGrps[ FEE_NUMBER_OF_CLUSTER_GROUPS ];

/* Configuration of Fee blocks */
extern const Fee_BlockConfigType  Fee_BlockConfig[ FEE_CRT_CFG_NR_OF_BLOCKS ];

#define FEE_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Fee_MemMap.h"
#ifdef __cplusplus
}
#endif

/** @} */

#endif /* FEE_CFG_H */

